server:
  name: go-sql-rest-api
  port: 8080

db:
  region: us-west-2
  access_key_id: AKIAYP22AGQ6VRBZZK6T
  secret_access_key: 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

log:
  level: info
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
