server:
  name: go-dynamodb-rest-api
  port: 8080

db:
  region: us-west-2

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
